device_type: lxc

job_name: lxc-pipeline-health
timeouts:
  job:
    minutes: 15
  action:
    minutes: 5
priority: medium
visibility: public

metadata:
  source: http://git.linaro.org/qa/test-definitions.git
  path: automated/linux/smoke/smoke.yaml

protocols:
  lava-lxc:
    name: pipeline-lxc-test
    template: debian
    distribution: debian
    release: stretch
    mirror: http://cdn-fastly.deb.debian.org/debian

actions:
- deploy:
    timeout:
      minutes: 30
    to: lxc
    os: debian

- boot:
    prompts:
    - 'root@(.*):/#'
    timeout:
      minutes: 5
    method: lxc

- test:
    timeout:
      minutes: 5
    definitions:
    - repository: http://git.linaro.org/qa/test-definitions.git
      from: git
      path: automated/linux/smoke/smoke.yaml
      name: smoke-tests
